[package]
name = "RustDropper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/maifest.html

[dependencies]
colored = "2.0.0"
downloader = "0.2.6"
subprocess = "0.2.9"
dirs = "4.0"